# Generated by Django 5.1.6 on 2025-02-10 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("monthly_base_fee", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="HobbyPlan",
            fields=[
                (
                    "plan_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="demo.plan",
                    ),
                ),
            ],
            bases=("demo.plan",),
        ),
        migrations.CreateModel(
            name="ProPlan",
            fields=[
                (
                    "plan_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="demo.plan",
                    ),
                ),
            ],
            bases=("demo.plan",),
        ),
    ]
